//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IMI.Turf.DataModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class Message
    {
        public int MessageId { get; set; }
        public int ServiceRequestId { get; set; }
        public string MessageBody { get; set; }
        public int FromUserId { get; set; }
        public int ToUserId { get; set; }
        public System.DateTime CreatedDate { get; set; }
    
        public virtual ServiceRequest ServiceRequest { get; set; }
    }
}
