//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IMI.Turf.DataModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class ServiceCategory
    {
        public ServiceCategory()
        {
            this.ServiceRequests = new HashSet<ServiceRequest>();
        }
    
        public int ServiceCategoryId { get; set; }
        public string CategoryName { get; set; }
        public string CategoryDescription { get; set; }
    
        public virtual ICollection<ServiceRequest> ServiceRequests { get; set; }
    }
}
