//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IMI.Turf.DataModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserProfile
    {
        public UserProfile()
        {
            this.Bids = new HashSet<Bid>();
            this.ServiceRequests = new HashSet<ServiceRequest>();
        }
    
        public int UserId { get; set; }
        public string UserName { get; set; }
    
        public virtual ICollection<Bid> Bids { get; set; }
        public virtual ICollection<ServiceRequest> ServiceRequests { get; set; }
    }
}
